Feat/keyple v2 implementation
eclipse/keyple-plugin-android-nfc-java-lib pull request #2
Opened 2021-06-17 14:26 UTC by ocfmem

2021-06-18 09:33 UTC, andrei-cristea requested changes

2021-06-18 11:04 UTC, andrei-cristea requested changes
Suite à la PR, nous avons vu que nous avions oublié de renommer dans la plugin API une méthode dans 3 interfaces. Nous avons donc effectué les mises à jour et pushé. Il faudrait donc que tu fasses un pull, que tu rebase ta branche et que tu la force push pour mettre à jour la PR. Vraiment désolé.

2021-06-21 07:30 UTC, ocfmem commented on keyple-plugins/android-nfc/.gitignore
> +/build
Par anticipatiion d'une évolution de la lib native NFC Android qui obligerai à maintenir 2 versions du plugin.

2021-06-21 07:32 UTC, ocfmem commented on keyple-plugins/android-nfc/gradle.properties
> +javaSourceLevel = 1.8
@brice-ruppen

2021-06-21 07:34 UTC, ocfmem commented on gradle.properties
> +javaSourceLevel = 1.8
Hum je pense que ce sont des changements ajoutés par @brice-ruppen, c'est surement pour pouvoir utiliser une version plus récente de Gradle.

2021-06-21 07:34 UTC, ocfmem commented on gradle.properties
> +javaSourceLevel = 1.8
Je vais creuser niveau impact mais je ne pense pas qu'il y'en ait.

2021-06-21 10:30 UTC, andrei-cristea requested changes

2021-06-21 10:30 UTC, andrei-cristea commented on keyple-plugins/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPlugin.kt
> + * {@inheritDoc}
Ca ne fonctionne pas sur des descriptions de classes ou d'interfaces.

2021-06-21 10:30 UTC, andrei-cristea commented on keyple-plugins/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginFactory.kt
> + * Interface for the Nfc Plugin Factory. Use AndroidNfcPluginFactoryProvider to retrieve
Il faudrait plutôt référencer les objets via le {@link ...}

2021-06-21 10:30 UTC, andrei-cristea commented on keyple-plugins/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcPluginFactoryProvider.kt
> + * <pre>SmartCardServiceProvider.getService().registerPlugin(AndroidNfcPluginFactoryProvider(this).getFactory())</pre>
Attention car cela crée une difficulté de maintenance au cas où des éléments seraient mis à jour dans Keyple Service

2021-06-21 10:30 UTC, andrei-cristea commented on keyple-plugins/android-nfc/src/main/kotlin/org/eclipse/keyple/plugin/android/nfc/AndroidNfcReader.kt
> + * {@inheritDoc}
idem

2021-06-21 14:46 UTC, andrei-cristea approved these changes

2021-06-21 15:45 UTC, merged